[build]
cmd = "go build -o tmp/main ./cmd/server"
bin = "tmp/main"
watch_dir = "."
watch_ext = ".go"

[build.main]
  full_dir = "."
  dir = "."
  cmd = "go build -o tmp/main ./cmd/server"
  args_binary = []

[misc]
  create_tmpl = false